package main

import (
	"market/internal/domain/attachment"
	"market/internal/domain/product"
	productaddon "market/internal/domain/product_addon"
	"market/internal/domain/user"
	"market/internal/routes"
	"market/pkg/cloud"
	"market/pkg/config"
	"market/pkg/database"
	"market/pkg/logger"
	"net/http"

	_ "market/docs" // docs is generated by Swagger CLI, you have to import it.
)

// @title           market API
// @version         1.0
// @description     API para gerenciamento de produtos e categorias para delivery
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@market.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {

	// Load environment configuration
	config.Load()

	// Initialize logger
	log := logger.NewLogger()

	// Initialize client database connection
	db := database.GetInstance(log)
	defer db.Close()

	cloud.NewCloudInstance(cloud.AWS_PROVIDER)

	// Initialize routes with handlers
	routeInstance := routes.NewRoutes(
		user.NewHandler(user.NewService(log)),
		product.NewHandler(product.NewService(log)),
		attachment.NewHandler(attachment.NewService(log)),
		// order.NewHandler(order.NewService(log)),
		productaddon.NewHandler(productaddon.NewService(log)),
	)

	log.Infof("🙏 Starting server on port %s 🙏", config.Get().SERVER_PORT)
	err := http.ListenAndServe(
		config.Get().SERVER_PORT,
		routeInstance,
	)

	if err != nil {
		log.Errorf("❌ failed to start server: %v", err)
		panic(err)
	}
}
